const tailwindAtRules = [
  "apply",
  "config",
  "custom-variant",
  "layer",
  "plugin",
  "reference",
  "screen",
  "source",
  "theme",
  "utility",
  "variant",
];

/** @type {import("stylelint").Config} */
const config = {
  defaultSeverity: "error",
  ignoreFiles: ["dist/**", "coverage/**"],
  reportInvalidScopeDisables: true,
  reportNeedlessDisables: true,
  rules: {
    "at-rule-no-unknown": [true, { ignoreAtRules: tailwindAtRules }],
    "block-no-empty": true,
    "color-no-invalid-hex": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": [
      true,
      { ignore: ["consecutive-duplicates-with-different-values"] },
    ],
    "declaration-block-no-shorthand-property-overrides": true,
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-no-unknown": [true, { ignoreFunctions: ["theme"] }],
    "media-feature-name-no-unknown": true,
    "media-query-no-invalid": true,
    "named-grid-areas-no-invalid": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": [true, { ignoreAtRules: tailwindAtRules }],
    "no-invalid-position-declaration": true,
    "no-irregular-whitespace": true,
    "property-no-unknown": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "string-no-newline": true,
    "syntax-string-no-invalid": true,
    "unit-no-unknown": true,
  },
};

export default config;
